### PR TITLE
Use setImmediate with callback in _close()

### PR DESCRIPTION
**Pull request by ralphtheninja**
Closes https://github.com/Level/level.js/issues/109

### CODE REVIEW

**Comment by vweevers** [comment]
Breaks the destroy tests.

**Comment by vweevers** [comment]
> Breaks the destroy tests.

I suspect that has something to with `deferred-leveldown`.

**Comment by ralphtheninja** [comment]
Yes I just found the same problem. Since we do `setImmediate()` then `db.db` is `DeferredLevelDOWN` object. I wouldn't mind picking option 1 either.

**Comment by vweevers** [comment]
> I wouldn't mind picking option 1 either.

Let's go with that 👍

**Comment by ralphtheninja** [comment]
I'll keep this PR open and fix that first.

**Pull request merged**
